exports.up = async (pgm) => {
  pgm.sql(`
    DELETE FROM training_modules;

    INSERT INTO training_modules (title, description, role, phase, order_index, content_markdown, estimated_duration_minutes, module_type, quiz_json, passing_score, created_at, updated_at) VALUES
    (
      'Playbook 101: Welcome to TUF',
      'Welcome to TUF Sports Apparel and the TUF Academy platform.',
      'REP',
      'LEVEL_1_OPERATOR',
      101,
      '## Learning Objective\\nWelcome to TUF Academy, the long-term certification, leadership development, and organizational operating system for TUF Sports Apparel.\\n\\n## Core Lesson\\nOur mission is to build self-sufficient territory developers capable of identifying, creating, advancing, closing, and expanding athletic program opportunities with minimal leadership intervention. TUF Academy is your leadership development system that powers this growth.',
      15,
      'MODULE',
      '[{"question": "What is the core mission of TUF Sports Apparel and TUF Academy?", "options": ["To sell cheap generic t-shirts", "To create self-sufficient territory developers who help athletic programs buy with speed, trust, and expansion", "To focus solely on professional league contracts", "To build retail stores in shopping malls"], "correctAnswer": "To create self-sufficient territory developers who help athletic programs buy with speed, trust, and expansion"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 102: The TUF Ecosystem',
      'Understand how TUF connects schools, coaches, and communities.',
      'REP',
      'LEVEL_1_OPERATOR',
      102,
      '## Learning Objective\\nLearn to view your market not as isolated transactional accounts, but as an interconnected ecosystem of athletic programs, schools, youth feeder programs, team stores, booster clubs, and local communities.\\n\\n## Core Lesson\\nThe TUF Ecosystem expands your reach beyond a single sport or buyer, securing long-term customer relationships and multi-lane revenue streams.',
      20,
      'MODULE',
      '[{"question": "What constitutes the TUF Ecosystem?", "options": ["Only the direct sales rep and the buyer", "The interconnected network of schools, youth feeders, team stores, booster clubs, and local communities", "A software tool for tracking inventory", "A delivery service for parcels"], "correctAnswer": "The interconnected network of schools, youth feeders, team stores, booster clubs, and local communities"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 103: Organizational Structure',
      'Understand the three divisions: Sales, Operations, and Brand Organizations.',
      'REP',
      'LEVEL_1_OPERATOR',
      103,
      '## Learning Objective\\nUnderstand the three core organizational layers that power TUF Sports Apparel.\\n\\n## Sales Organization\\n- Composed of Territory Account Executives and Directors.\\n- Responsible for territory management, prospecting, discovery, closing, and account expansion.\\n\\n## Operations Organization\\n- Handles custom vendor routing, inventory management, production, fulfillment, and customer service.\\n- Ensures design mockups translate to accurate physical products.\\n\\n## Brand Organization\\n- Manages the visual identity of TUF, marketing materials, template design systems, and public positioning.\\n- Collaborates with sales to provide presentation templates and assets.',
      25,
      'MODULE',
      '[{"question": "Which department in TUF is responsible for vendor routing and fulfillment operations?", "options": ["Sales Organization", "Operations Organization", "Brand Organization", "Creative Design Desk"], "correctAnswer": "Operations Organization"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 104: Systems & Accountability',
      'Understand TUF Ops systems, daily touch tracking, and performance standards.',
      'REP',
      'LEVEL_1_OPERATOR',
      104,
      '## Learning Objective\\nLearn to navigate the TUF Ops portal, track daily prospect touches, maintain clean CRM notes, and follow our strict accountability guidelines.\\n\\n## Core Lesson\\nSelf-sufficiency requires systematic discipline. Every territory developer must log their activities, update opportunity stages, define clear next steps, and maintain the 4-orders-per-month standard.',
      20,
      'MODULE',
      '[{"question": "What is the standard monthly order floor for a TUF rep?", "options": ["1 order per month", "4 orders per month", "10 orders per month", "No specific floor"], "correctAnswer": "4 orders per month"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 201: School Athletics Ecosystem',
      'Navigate athletic programs, athletic directors, and sport seasons.',
      'REP',
      'LEVEL_2_PRODUCT',
      201,
      '## Learning Objective\\nLearn how school athletic departments operate, including purchasing hierarchies, budget cycles, and seasonal timelines.\\n\\n## Core Lesson\\nThe Athletic Director (AD) is the primary gatekeeper, but individual head coaches hold massive design and brand influence. Managing both is crucial for a successful territory relationship.',
      25,
      'MODULE',
      '[{"question": "Who is the primary gatekeeper for school athletic purchases?", "options": ["The school principal", "The Athletic Director (AD)", "The student council president", "The head coach of a single sport"], "correctAnswer": "The Athletic Director (AD)"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 202: Product Knowledge',
      'Master custom uniforms, materials, sizes, and player pack structures.',
      'REP',
      'LEVEL_2_PRODUCT',
      202,
      '## Learning Objective\\nDevelop expertise in TUF product lines: custom uniform fabrics, durability specs, mockups, and player pack setups.\\n\\n## Core Lesson\\nPlayer packs simplify order aggregation by shipping individually to parents, saving head coaches dozens of distribution hours and reducing team logistics friction.',
      30,
      'MODULE',
      '[{"question": "What is a key benefit of TUF player packs?", "options": ["They are shipped individually to each parent, saving coaches distribution time", "They only come in one size", "They are sold at retail stores", "They require manual sorting by the athletic department"], "correctAnswer": "They are shipped individually to each parent, saving coaches distribution time"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 203: Prospecting',
      'Master school research, contact gathering, LinkedIn outreach, social selling, and territory management.',
      'REP',
      'LEVEL_2_PRODUCT',
      203,
      '## Learning Objective\\nEstablish a structured prospecting workflow to build your pipeline.\\n\\n## Core Lesson\\n- **School Research**: Analyze assigned territory schools, their current brands, and historical purchasing habits.\\n- **Contact Gathering**: Identify Athletic Directors, head coaches, and booster presidents.\\n- **LinkedIn Outreach & Social Selling**: Initiate contact professionally by delivering valuable insights rather than generic sales pitches.\\n- **Territory Management**: Group schools geographically to optimize physical visits and establish regional density.',
      30,
      'MODULE',
      '[{"question": "What is the first step in TUF territory prospecting?", "options": ["Pitching a contract cold via phone", "Researching the school, gathering key contact info, and mapping existing athletic brands", "Sending free samples to the school main office", "Showing up unannounced to a team practice"], "correctAnswer": "Researching the school, gathering key contact info, and mapping existing athletic brands"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 204: First Contact',
      'Master cold outreach, scripts, emails, and securing the first meeting.',
      'REP',
      'LEVEL_2_PRODUCT',
      204,
      '## Learning Objective\\nInitiate outreach that breaks through the noise and secures a discovery meeting.\\n\\n## Core Lesson\\nLeverage TUF commercial insights. Introduce the TUF platform by addressing common vendor friction points: late shipments, poor communication, and complex ordering processes.',
      25,
      'MODULE',
      '[{"question": "What is the main goal of your first contact with a coach?", "options": ["To close a uniform order immediately", "To schedule a discovery meeting and establish trust", "To ask for their personal credit card info", "To ask for an exclusive multi-year contract"], "correctAnswer": "To schedule a discovery meeting and establish trust"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 205: Discovery',
      'Uncover athletic budget constraints, vendor pain points, and sport timelines.',
      'REP',
      'LEVEL_2_PRODUCT',
      205,
      '## Learning Objective\\nConduct structured discovery to diagnose potential client pain points and buying readiness.\\n\\n## Core Lesson\\nNever lead with products or pricing. Lead with diagnostic questions to uncover current vendor friction: \\"What was your biggest headache with your last uniform delivery timeline?\\" Use the gaps discovered to position TUF solutions.',
      25,
      'MODULE',
      '[{"question": "What diagnostic question best uncovers current vendor service friction?", "options": ["Can we beat your current pricing by 10%", "What was your biggest headache with your last uniform delivery timeline?", "Will you sign this contract today?", "Which sport has the largest budget?"], "correctAnswer": "What was your biggest headache with your last uniform delivery timeline?"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 206: Presentations & Mockups',
      'Create high-converting mockup requests and present visual custom designs to coaches.',
      'REP',
      'LEVEL_2_PRODUCT',
      206,
      '## Learning Objective\\nConvert interest into visual design requests using our design desk.\\n\\n## Core Lesson\\nCustom mockups are our highest-converting sales trigger. Upload correct vector artwork and precise school colors in TUF Ops to enable our design desk to deliver stunning, error-free mockups that coaches can visualize on their team.',
      25,
      'MODULE',
      '[{"question": "Why is uploading correct vector artwork crucial for mockup requests?", "options": ["It ensures high-quality mockups and prevents production delays", "It is required for tax reporting", "It is only used for archiving", "It automatically generates a pricing quote"], "correctAnswer": "It ensures high-quality mockups and prevents production delays"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 207: Closing Business',
      'Overcome final hurdles, secure design approval, and transition to orders.',
      'REP',
      'LEVEL_2_PRODUCT',
      207,
      '## Learning Objective\\nWalk coaches through final mockup approvals, size selections, and order submissions.\\n\\n## Core Lesson\\nClosing is about coordination. Review the mockups together, confirm quantities, order deadlines, and have them sign the mockup sign-off. This transitions the deal from opportunity to active order.',
      25,
      'MODULE',
      '[{"question": "How do you secure final uniform approval from a coach?", "options": ["Wait for them to call you back", "Review the mockup together, confirm quantities, timelines, and have them sign the mockup sign-off", "Offer a larger discount without checking margins", "Assume they approve if they don\'\'t reply in 48 hours"], "correctAnswer": "Review the mockup together, confirm quantities, timelines, and have them sign the mockup sign-off"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 208: Account Expansion',
      'Sell multi-sport solutions, team stores, coaches gear, travel programs, and letterman jackets.',
      'REP',
      'LEVEL_2_PRODUCT',
      208,
      '## Learning Objective\\nExpand a single uniform order into a multi-lane relationship.\\n\\n## Core Lesson\\nLeverage a successful football uniform delivery. Immediately introduce coaches gear, parent/fan team stores, travel programs, and letterman jackets. Expansion turns a small transactional relationship into a major account.',
      30,
      'MODULE',
      '[{"question": "Which of the following is an effective account expansion strategy?", "options": ["Only selling uniforms to the head coach", "Leveraging a football uniform sale to launch a team store, coaches gear, and letterman jackets", "Moving to a different school immediately after a sale", "Failing to ask for athletic director introductions"], "correctAnswer": "Leveraging a football uniform sale to launch a team store, coaches gear, and letterman jackets"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 301: Lane Penetration',
      'Understand that One School = Multiple Lanes, and map individual sport/product revenue streams.',
      'REP',
      'LEVEL_3_TERRITORY',
      301,
      '## Learning Objective\\nAdopt the core mindset: One School \u2260 One Sale. One School = Multiple Lanes.\\n\\n## Core Lesson\\nEvery school has independent revenue streams: Football uniforms, basketball jerseys, baseball gear, booster stores, and letterman jackets. To penetrate a territory, you must map and win these lanes independently.',
      25,
      'MODULE',
      '[{"question": "What does Lane Penetration mean in the TUF operating model?", "options": ["Driving in the fast lane to school visits", "Expanding beyond a single sport or product line to capture multiple lanes in a school", "Limiting sales to one sport per school", "Selling only letterman jackets"], "correctAnswer": "Expanding beyond a single sport or product line to capture multiple lanes in a school"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 302: Feeder Program Extraction',
      'Tap youth football leagues, club volleyball, travel basketball, and community sports.',
      'REP',
      'LEVEL_3_TERRITORY',
      302,
      '## Learning Objective\\nMap and target youth programs feeding into your territory high schools.\\n\\n## Core Lesson\\nYouth leagues, middle schools, and club travel programs feed directly into high school systems. Winning these feeder programs establishes brand loyalty early, increases revenue, and expands your territory footprint.',
      25,
      'MODULE',
      '[{"question": "How do youth feeder programs benefit your high school account?", "options": ["They have no connection to high schools", "They build early brand loyalty and expand your lane revenue to younger age brackets", "They are run directly by the school principal", "They replace the high school team store"], "correctAnswer": "They build early brand loyalty and expand your lane revenue to younger age brackets"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 303: Building a TUF School',
      'Turn a single account into a multi-lane, multi-year relationship.',
      'REP',
      'LEVEL_3_TERRITORY',
      303,
      '## Learning Objective\\nTransform accounts into long-term strategic partners.\\n\\n## Core Lesson\\nA \u201cTUF School\u201d is an account with multiple active lanes, youth feeder alignments, and a long-term preferred vendor relationship. Transition accounts from simple buyers to fully integrated TUF Schools.',
      30,
      'MODULE',
      '[{"question": "What distinguishes a \'\'TUF School\'\' from a standard account?", "options": ["A school with a single active uniform order", "A school with multiple active lanes, youth feeders, and a long-term relationship with TUF", "Any school within your assigned territory", "A school that has locked you out"], "correctAnswer": "A school with multiple active lanes, youth feeders, and a long-term relationship with TUF"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 401: From Rep to Leader',
      'Transition from individual contributor to coaching and guiding other reps.',
      'REP',
      'LEVEL_4_SALES',
      401,
      '## Learning Objective\\nTransition from managing your own territory to leading, enabling, and scaling a team of reps.\\n\\n## Core Lesson\\nAs a Director, your success is measured by the performance of your Territory Account Executives. Focus on system adherence, accountability, and metric tracking.',
      30,
      'MODULE',
      '[{"question": "What is the primary shift in responsibility when moving from Rep to Director?", "options": ["Doing all the selling yourself", "Enabling and coaching your team of reps to perform at their best", "Working fewer hours", "Ignoring company operations"], "correctAnswer": "Enabling and coaching your team of reps to perform at their best"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 402: Coaching Conversations',
      'Run structured pipeline reviews and rubrics-based coaching.',
      'REP',
      'LEVEL_4_SALES',
      402,
      '## Learning Objective\\nLearn to host effective coaching sessions using rubric-based frameworks.\\n\\n## Core Lesson\\nDo not just ask \\"When will this deal close?\\" Instead, use standard rubrics to review active opportunities: next action dates, contact depth, lanes identified, and potential friction notes.',
      25,
      'MODULE',
      '[{"question": "How should a Director guide a rep during a coaching conversation?", "options": ["Tell them exactly what to do without asking questions", "Use rubric-based questions to help them identify next steps and expansion paths", "Do the sales calls for them", "Reprimand them for any deal delays"], "correctAnswer": "Use rubric-based questions to help them identify next steps and expansion paths"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 403: Territory Management',
      'Plan coverage, allocate leads, and monitor regional metrics.',
      'REP',
      'LEVEL_4_SALES',
      403,
      '## Learning Objective\\nManage and optimize the school books and leads in your territory scope.\\n\\n## Core Lesson\\nEnsure optimal account coverage. Reassign untouched schools, track activity streaks, identify high-risk accounts, and coordinate resource allocation for regional campaigns.',
      25,
      'MODULE',
      '[{"question": "What is the main goal of director-level territory management?", "options": ["Letting reps pick schools randomly", "Ensuring optimal account coverage, assigning lead pools, and monitoring territory health", "Taking over the top accounts for yourself", "Closing low-value opportunities"], "correctAnswer": "Ensuring optimal account coverage, assigning lead pools, and monitoring territory health"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 404: Academy Certification',
      'Manage rep onboarding, checkoff requirements, and system unlocks.',
      'REP',
      'LEVEL_4_SALES',
      404,
      '## Learning Objective\\nUnderstand the certification criteria and sign-off process for new reps.\\n\\n## Core Lesson\\nVerify all four certification blocks before signing off on a rep: completed Academy playbooks, filed HR paperwork, passed Locker Room simulator scenarios, and Director verification.',
      25,
      'MODULE',
      '[{"question": "What four requirements must a Director verify before a rep is activated?", "options": ["Completed playbooks, HR docs, practical exercise, and director sign-off", "First sale, vector logo upload, quiz score, and phone log", "Sample kit delivery, phone call, simulation pass, and signature", "CRM account creation, profile photo, bio, and email"], "correctAnswer": "Completed playbooks, HR docs, practical exercise, and director sign-off"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 405: Performance Management',
      'Manage performance standards, scorecards, and accountability.',
      'REP',
      'LEVEL_4_SALES',
      405,
      '## Learning Objective\\nIdentify and correct performance gaps within your sales team.\\n\\n## Core Lesson\\nWhen a rep falls below the 4-orders-per-month standard, review activity inputs: daily prospect touches, note completeness, next action dates, and simulator practice sessions.',
      25,
      'MODULE',
      '[{"question": "What standard should be reviewed when a rep falls below the monthly floor?", "options": ["Daily prospecting touches, CRM note quality, next action dates, and simulator practice", "Changing their role to Admin", "Giving them free orders", "Telling them to stop calling schools"], "correctAnswer": "Daily prospecting touches, CRM note quality, next action dates, and simulator practice"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 501: Building Leaders',
      'Develop Directors and build leadership depth.',
      'REP',
      'LEVEL_5_EXPANSION',
      501,
      '## Learning Objective\\nIdentify and develop Territory Account Executives into capable Directors.\\n\\n## Core Lesson\\nRegional Directors build leaders. Train directors in performance management, coaching frameworks, and systems accountability to build leadership depth in your region.',
      30,
      'MODULE',
      '[{"question": "What is a Regional Director\'\'s role in building leaders?", "options": ["Coaching Directors on performance management and coaching skills", "Selling to school districts", "Managing individual rep pipelines", "Creating marketing flyers"], "correctAnswer": "Coaching Directors on performance management and coaching skills"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 502: Recruiting Systems',
      'Identify, recruit, and onboard talent.',
      'REP',
      'LEVEL_5_EXPANSION',
      502,
      '## Learning Objective\\nDeploy structured hiring and onboarding systems to scale your territory.\\n\\n## Core Lesson\\nUse systematic, rubric-based recruiting. Look for self-sufficient territory developers who demonstrate ownership, sales discipline, and alignment with TUF values.',
      25,
      'MODULE',
      '[{"question": "What is key to recruiting successful reps?", "options": ["Hiring based on resume alone", "Using structured competency assessments and seeking self-sufficient territory developers", "Selecting people who only want passive income", "Automated hiring without interviews"], "correctAnswer": "Using structured competency assessments and seeking self-sufficient territory developers"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 503: Regional Expansion',
      'Launch new territories and scale regional presence.',
      'REP',
      'LEVEL_5_EXPANSION',
      503,
      '## Learning Objective\\nScale operations by launching adjacent and new geographic territories.\\n\\n## Core Lesson\\nRegional expansion depends on playbook replication. Hire a native territory developer, seed them with standard playbooks, connect them with our operations desk, and support them through local leadership.',
      25,
      'MODULE',
      '[{"question": "How do you scale regional operations effectively?", "options": ["By duplicating standard operating playbooks and recruiting native leaders in new territories", "By expanding without local leaders", "By lowering commission rates", "By selling uniforms at lower margins"], "correctAnswer": "By duplicating standard operating playbooks and recruiting native leaders in new territories"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 601: The Founder Trap',
      'Move from founder-led sales to scalable, process-driven leadership layers.',
      'REP',
      'SPECIALIZED_TRACKS',
      601,
      '## Learning Objective\\nTransition the organization from founder-led sales to a systemized, process-driven architecture.\\n\\n## Core Lesson\\nThe Founder Trap occurs when all operations depend on a single founder\'\'s personal energy. Escaping this requires documented playbooks, certified leadership layers, and standardized accountability.',
      30,
      'MODULE',
      '[{"question": "How do you escape the \'\'Founder Trap\'\'?", "options": ["Founder makes all the major decisions forever", "Building systemized processes, playbooks, and delegating authority to certified leaders", "Selling the company", "Hiring more administrative assistants"], "correctAnswer": "Building systemized processes, playbooks, and delegating authority to certified leaders"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 602: Leadership Layers',
      'Structure the organization for long-term growth and accountability.',
      'REP',
      'SPECIALIZED_TRACKS',
      602,
      '## Learning Objective\\nUnderstand the coordination between Sales, Operations, and Brand leadership layers.\\n\\n## Core Lesson\\nStructure clear growth and accountability paths. Build functional leadership layers that coordinate sales enablement, product fulfillment, and brand integrity.',
      25,
      'MODULE',
      '[{"question": "What is the purpose of structured leadership layers at TUF?", "options": ["To slow down decision-making", "To align authority, coordinate sales/operations/brand, and foster professional growth paths", "To replace all human interactions with AI", "To eliminate the need for training"], "correctAnswer": "To align authority, coordinate sales/operations/brand, and foster professional growth paths"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 603: Building The TUF Ecosystem',
      'Develop high-level partnerships and expand the global TUF ecosystem.',
      'REP',
      'SPECIALIZED_TRACKS',
      603,
      '## Learning Objective\\nFormulate the long-term strategic vision for the global TUF Ecosystem.\\n\\n## Core Lesson\\nOur goal is to build an interconnected ecosystem spanning team apparel, community sports, equipment partnerships, and media channels, establishing TUF as the operating system for school athletics.',
      30,
      'MODULE',
      '[{"question": "What is the ultimate vision of the TUF Ecosystem?", "options": ["Creating an interconnected apparel, equipment, and media network that dominates school athletics", "Becoming a small local supplier", "Selling direct-to-consumer only", "Focusing on custom socks"], "correctAnswer": "Creating an interconnected apparel, equipment, and media network that dominates school athletics"}]'::jsonb,
      85,
      NOW(),
      NOW()
    );
  `);
};

exports.down = async (pgm) => {
  pgm.sql(`
    DELETE FROM training_modules WHERE order_index >= 101 AND order_index <= 603;
  `);
};
