exports.up = async (pgm) => {
  pgm.sql(`
    DELETE FROM training_modules;

    INSERT INTO training_modules (title, description, role, phase, order_index, content_markdown, estimated_duration_minutes, module_type, quiz_json, passing_score, created_at, updated_at) VALUES
    (
      'Playbook 101: Welcome to TUF',
      'Welcome to TUF Sports Apparel and the TUF Academy platform.',
      'REP',
      'LEVEL_1_OPERATOR',
      101,
      '## Learning Objective\\nWelcome to TUF Academy, the long-term certification, leadership development, and organizational operating system for TUF Sports Apparel.\\n\\n## Training Explanation\\nWelcome to TUF Academy, the long-term certification, leadership development, and organizational operating system for TUF Sports Apparel. Our mission is to build self-sufficient territory developers capable of identifying, creating, advancing, closing, and expanding athletic program opportunities with minimal leadership intervention. TUF Academy is your leadership development system that powers this growth.\\n\\nAt TUF, we operate with clear and strict guardrails. Every Territory Account Executive (TAE) has a hard cap of 25 active opportunities in their pipeline to prevent deal stagnation and maintain high touch quality. Deals must maintain a strict 45% Gross Margin Floor to ensure profitability, with any discount up to 10% requiring written approval from the Regional Director. We manage custom sublimation through our specialized facility in Pakistan (4-week production timeline) and quick-turn fulfillment via local Midwest printing (7-day turnaround timeline).\\n\\n## Rep Actions\\n1. Explore the layout of the TUF Academy dashboard.\\n2. Verify that your user credentials and profile details are correct.\\n3. Review the overall structure of the Combine phases.\\n\\n## Field Language\\nWhen introducing TUF: "We help athletic programs customize, order, and distribute premium custom sportswear and fan gear seamlessly, giving coaches their time back while maintaining strict brand consistency."\\n\\n## What Done Means\\nRead the playbook sections completely and pass the certification check question.\\n\\n## Practical Checkpoint\\nEnsure you can navigate to the Training portal and see the 4-Phase checklist.',
      15,
      'MODULE',
      '[{"question": "As a newly onboarded Territory Account Executive, a local high school coach asks you how TUF Sports Apparel differs from traditional generic team dealers. Based on Playbook 101, how should you position TUF\'\'s core mission?", "options": ["\\"We are a standard online e-commerce shop that sells bulk blank shirts at wholesale prices.\\"", "\\"We build self-sufficient territory developers who partner with athletic programs to consolidate buying, run transparent team stores, and give coaches their time back.\\"", "\\"We focus on securing exclusive multi-year sponsorships with professional sports franchises and colleges.\\"", "\\"We are a local print shop that does quick screen printing for local charity runs and community festivals.\\""], "correctAnswer": "\\"We build self-sufficient territory developers who partner with athletic programs to consolidate buying, run transparent team stores, and give coaches their time back.\\""}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 102: The TUF Ecosystem',
      'Understand how TUF connects schools, coaches, and communities.',
      'REP',
      'LEVEL_1_OPERATOR',
      102,
      '## Learning Objective\\nLearn to view your market not as isolated transactional accounts, but as an interconnected ecosystem of athletic programs, schools, youth feeder programs, team stores, booster clubs, and local communities.\\n\\n## Training Explanation\\nLearn to view your market not as isolated transactional accounts, but as an interconnected ecosystem of athletic programs, schools, youth feeder programs, team stores, booster clubs, and local communities. The TUF Ecosystem expands your reach beyond a single sport or buyer, securing long-term customer relationships and multi-lane revenue streams.\\n\\nA single school is not one sale; it is a gateway to multiple sport lanes. By executing our Ecosystem Referral Script, you can bridge varsity programs with youth feeder associations. This aligns the entire community\'\'s brand, standardizes custom apparel, and creates fundraising opportunities. When youth programs run in the same colors and logo styles as the varsity team, the community brand becomes consistent, and 5% of all youth team store sales can be funneled back to support the high school\'\'s varsity athletic department.\\n\\n## Rep Actions\\n1. Research the youth sports associations that feed into your target high school\'\'s athletic programs.\\n2. Identify booster club officers and their primary funding priorities for the upcoming season.\\n3. Use the Ecosystem Referral Script on every varsity closing call to secure youth league introductions.\\n\\n## Field Language\\nObjection: "We only order for our varsity football team."\\nResponse: "We look at the whole school ecosystem. By connecting your youth programs and launching a parent fan store, we can fundraise for your varsity program and build community brand consistency."\\n\\nEcosystem Referral Script: "Coach, now that we have your varsity squad set up with their game kits, we want to make sure the middle school and youth feeder programs are running the exact same brand assets. Who is the director of your youth association? I want to reach out to them, get their kids in the same colors, and route 5% of their team store sales directly back into your varsity booster account."\\n\\n## What Done Means\\nUnderstand all elements of the local athletic ecosystem and pass the check.\\n\\n## Practical Checkpoint\\nIdentify at least one community sports or youth program affiliated with your main assigned school.',
      20,
      'MODULE',
      '[{"question": "You have successfully secured the varsity football uniform order. Which of the following is the most strategic execution of the Ecosystem Referral Script to expand within the TUF Ecosystem?", "options": ["Ask the coach for an introduction to the local youth football association director to align their apparel designs and route 5% of their team store sales to the varsity booster club.", "Offer a 15% discount on the varsity uniforms to bypass the gross margin floor.", "Move on to a different county and ignore the local youth leagues since they have lower budgets.", "Ask the booster club to purchase generic off-brand shirts from a local screen printer."], "correctAnswer": "Ask the coach for an introduction to the local youth football association director to align their apparel designs and route 5% of their team store sales to the varsity booster club."}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 103: Organizational Structure',
      'Understand the three divisions: Sales, Operations, and Brand Organizations.',
      'REP',
      'LEVEL_1_OPERATOR',
      103,
      '## Learning Objective\\nUnderstand the three core organizational layers that power TUF Sports Apparel: Sales, Operations, and Brand.\\n\\n## Training Explanation\\nUnderstand the three core organizational layers that power TUF Sports Apparel: Sales, Operations, and Brand. Sales handles territory development, prospecting, and closing. Operations handles vendor routing, manufacturing logistics, inventory, and fulfillment. Brand manages the visual identity, templates, positionings, and custom mockup creation.\\n\\nSelf-sufficiency requires understanding how to interface with Operations and Brand to deliver on customer promises. Our Brand design desk turns around mockups in 24 hours. Once the design is approved, Operations handles manufacturing routing. Sublimated uniforms are manufactured in our partner facility in Pakistan to maximize quality and margins (4-week production timeline). Small-run or urgent items are sent to our Midwest print facility (7-day turnaround) but are subject to a Workload Capacity Cap to protect delivery times.\\n\\n## Rep Actions\\n1. Review the roles within the Sales, Operations, and Brand departments.\\n2. Learn the process for requesting custom designs from the Brand design desk.\\n3. Understand when to route orders to the Midwest facility vs. the Pakistan facility.\\n\\n## Field Language\\nWhen explaining coordination: "Our Sales, Operations, and Brand teams work in absolute coordination so that custom design mockups are turned around in 24 hours, and custom orders ship on time, every time."\\n\\n## What Done Means\\nPass the structure quiz demonstrating knowledge of department responsibilities.\\n\\n## Practical Checkpoint\\nIdentify which department is responsible for vendor routing and custom packaging configurations.',
      25,
      'MODULE',
      '[{"question": "A coach approves their varsity soccer uniform mockup but needs 10 additional practice shirts printed within 8 days. How should you route these items based on TUF\'\'s organizational structure?", "options": ["Route the practice shirts to the local Midwest print facility (7-day turnaround) and the main uniform order to the Pakistan facility (4-week timeline) through the Operations department.", "Submit both orders to the Pakistan facility and hope they arrive within 8 days.", "Create the designs yourself and print the practice shirts at a local hobby shop.", "Tell the coach that Operations cannot process orders of fewer than 50 units."], "correctAnswer": "Route the practice shirts to the local Midwest print facility (7-day turnaround) and the main uniform order to the Pakistan facility (4-week timeline) through the Operations department."}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 104: Systems & Accountability',
      'Understand TUF Ops systems, daily touch tracking, and performance standards.',
      'REP',
      'LEVEL_1_OPERATOR',
      104,
      '## Learning Objective\\nLearn to navigate the TUF Ops portal, track daily prospect touches, maintain clean CRM notes, and follow our strict accountability guidelines.\\n\\n## Training Explanation\\nLearn to navigate the TUF Ops portal, track daily prospect touches, maintain clean CRM notes, and follow our strict accountability guidelines. Every territory developer must log their activities, update opportunity stages, define clear next steps, and maintain the 4-orders-per-month standard.\\n\\nTo keep the pipeline moving, reps are capped at 25 active opportunities. If a deal stalls, it must be archived or closed. All opportunities must meet a 45% Gross Margin Floor. Any discount up to 10% must receive written approval from the Regional Director before submission. Any discount exceeding 10% is blocked. Every opportunity must go through the Mockup Discovery Gate before a design request is sent to the Brand team.\\n\\n## Rep Actions\\n1. Log in to TUF Ops and navigate the Organizations and Opportunities screens.\\n2. Maintain your active pipeline under the 25-opportunity cap and log all touches.\\n3. Obtain written Director approval for any discount up to 10% before submitting.\\n\\n## Field Language\\n"Our accountability standards ensure that no prospect is left without a clear next step, and every order is tracked with 100% transparency in TUF Ops."\\n\\n## What Done Means\\nPass the accountability standard quiz and understand the 4-orders-per-month minimum floor.\\n\\n## Practical Checkpoint\\nVerify that you can view your pipeline on the Opportunities page and know where to log a daily touch.',
      20,
      'MODULE',
      '[{"question": "You have 25 active opportunities and want to log a new lead. A coach is also requesting a 12% discount on a jersey order. How do you handle this under TUF\'\'s systems and accountability rules?", "options": ["Log the new lead as a sub-account to bypass the 25-opportunity cap and grant the 12% discount to secure the order.", "Archive or close an inactive opportunity to make room for the new lead, and refuse the 12% discount as the absolute maximum discount is 10% with written Director approval, keeping the margin above the 45% floor.", "Request that the Operations team manually log the order to bypass CRM limits, and apply a 10% discount without approval.", "Delete 5 pending opportunities to clear pipeline space and tell the coach that discounts are only approved for professional teams."], "correctAnswer": "Archive or close an inactive opportunity to make room for the new lead, and refuse the 12% discount as the absolute maximum discount is 10% with written Director approval, keeping the margin above the 45% floor."}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 201: School Athletics Ecosystem',
      'Navigate athletic programs, athletic directors, and sport seasons.',
      'REP',
      'LEVEL_2_PRODUCT',
      201,
      '## Learning Objective\\nLearn how school athletic departments operate, including purchasing hierarchies, budget cycles, and seasonal timelines.\\n\\n## Training Explanation\\nLearn how school athletic departments operate, including purchasing hierarchies, budget cycles, and seasonal timelines. School athletic purchasing operates under a dual-gate system. The Athletic Director (AD) is the primary gatekeeper who controls school-wide brand contracts, PO systems, and budget allocations. The head coaches hold massive influence over design preferences, player pack selections, and sport-specific timelines.\\n\\nTo win a school, you must build relationships with both. Pitch the AD on brand consistency, consolidated ordering, and fan gear fundraising. Pitch the coach on high-performance fabrics (TUF SHIFT and TUF GRIND) and saving time by shipping player packs directly to parents.\\n\\n## Rep Actions\\n1. Map out the sports seasons (Fall, Winter, Spring) for your assigned schools.\\n2. Identify the Athletic Directors and their administrative assistants.\\n3. List the head coaches for high-priority sports (Football, Basketball, Baseball).\\n\\n## Field Language\\nPitching the AD: "Mr./Ms. AD, we work with athletic directors to bring brand consistency across all sports, consolidate purchasing, and launch fan stores that generate revenue for the booster club."\\n\\n## What Done Means\\nIdentify the gatekeeper roles and pass the school ecosystem quiz.\\n\\n## Practical Checkpoint\\nLook up the contact details of the AD at your primary assigned school.',
      25,
      'MODULE',
      '[{"question": "An Athletic Director states they have an exclusive contract with a major national brand, but the head basketball coach wants to buy custom uniforms from TUF. How do you navigate this school hierarchy?", "options": ["Sell directly to the basketball coach and bill the parents via a player pack store, completely ignoring the AD.", "Propose a meeting with the AD to demonstrate how our booster-funded fan stores can operate alongside their current contract, generating revenue for the school while introducing brand consistency.", "Inform the coach that we cannot do business due to the exclusive contract and archive the lead.", "Ask the basketball coach to request a formal exception from the school board to cancel the contract."], "correctAnswer": "Propose a meeting with the AD to demonstrate how our booster-funded fan stores can operate alongside their current contract, generating revenue for the school while introducing brand consistency."}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 202: Product Knowledge',
      'Master custom uniforms, materials, sizes, and player pack structures.',
      'REP',
      'LEVEL_2_PRODUCT',
      202,
      '## Learning Objective\\nDevelop expertise in TUF product lines: custom uniform fabrics, durability specs, mockups, and player pack setups.\\n\\n## Training Explanation\\nDevelop expertise in TUF product lines: custom uniform fabrics, durability specs, mockups, and player pack setups. We offer two primary performance fabrics. TUF SHIFT is our premium, ultra-lightweight, moisture-wicking polyester/spandex blend engineered for elite breathability and speed (ideal for basketball and track). TUF GRIND is our high-durability, abrasion-resistant, double-knit fabric engineered for heavy-impact, contact sports like football.\\n\\nOur supply chain offers two options. Sublimated uniforms are manufactured at our specialized facility in Pakistan, taking 4 weeks and yielding high gross margins. Mid-season emergency orders or local event gear are routed to our Midwest facility, taking 7 days but at a higher cost.\\n\\n## Rep Actions\\n1. Memorize the difference between TUF SHIFT (lightweight breathability) and TUF GRIND (high durability) fabrics.\\n2. Educate coaches on the 4-week Pakistan sublimation timeline vs. the 7-day Midwest print timeline.\\n3. Structure player packs so that they are shipped directly to parents\'\' homes, saving coaches distribution time.\\n\\n## Field Language\\nExplaining fabrics: "Our TUF SHIFT fabric is engineered for elite breathability and rapid moisture management, while TUF GRIND is built to withstand high-contact sports without sacrificing player comfort."\\n\\n## What Done Means\\nDemonstrate clear understanding of custom uniform specifications and player pack delivery logistics.\\n\\n## Practical Checkpoint\\nExplain the difference between TUF SHIFT and TUF GRIND fabrics.',
      30,
      'MODULE',
      '[{"question": "A football coach needs game uniforms for the season opener in 5 weeks, and also needs 10 replacement jerseys for new roster additions within 9 days. What is the correct product and production routing plan?", "options": ["Order the game uniforms in TUF GRIND fabric routed to our Pakistan facility (4-week timeline), and the replacement jerseys in TUF GRIND fabric routed to our local Midwest facility (7-day timeline).", "Order both the game uniforms and replacement jerseys in TUF SHIFT fabric routed to Pakistan.", "Order both in TUF GRIND fabric routed to the Midwest facility, ignoring the gross margin floor.", "Tell the coach that custom replacement jerseys cannot be produced in less than 4 weeks."], "correctAnswer": "Order the game uniforms in TUF GRIND fabric routed to our Pakistan facility (4-week timeline), and the replacement jerseys in TUF GRIND fabric routed to our local Midwest facility (7-day timeline)."}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 203: Prospecting',
      'Master school research, contact gathering, LinkedIn outreach, social selling, and territory management.',
      'REP',
      'LEVEL_2_PRODUCT',
      203,
      '## Learning Objective\\nEstablish a structured prospecting workflow to build your pipeline.\\n\\n## Training Explanation\\nEstablish a structured prospecting workflow to build your pipeline. Prospecting is about intelligence and geography. Analyze assigned territory schools, their current brands, and historical purchasing habits. Identify ADs, head coaches, and booster presidents. Group schools geographically to optimize physical visits and establish regional density.\\n\\nUse social selling to identify schools with mismatched apparel. Research their booster activity and reach out to head coaches with custom outreach. Always research the school\'\'s colors, mascot, and current brand before making contact.\\n\\n## Rep Actions\\n1. Open the Territory Command Map and view your assigned zone.\\n2. Research competitors currently supplying the teams in your territory.\\n3. Compile a lead list of coaches and ADs with active emails and phone numbers.\\n\\n## Field Language\\nSocial selling outreach: "Coach, saw your team\'\'s great run last season. I put together a mockup design that matches your school colors and tradition. Love to send it over to get your feedback."\\n\\n## What Done Means\\nComplete the prospecting quiz demonstrating structured territory mapping knowledge.\\n\\n## Practical Checkpoint\\nLocate three schools in your assigned territory on the Map page.',
      30,
      'MODULE',
      '[{"question": "You are researching a high-priority school in your territory. You notice their basketball team wears one brand, their track team wears another, and their booster club runs a separate storefront. What is your strategic prospecting approach?", "options": ["Contact the head basketball coach to sell them jerseys, ignoring the other sports and the booster club.", "Profile the school\'\'s active booster club, map the coaches for all sports, and reach out to the AD proposing a consolidated brand program to unify their look.", "Cold call the school main office and ask for the athletic department\'\'s budget spreadsheets.", "Send a generic wholesale price catalog to the booster club\'\'s general inbox."], "correctAnswer": "Profile the school\'\'s active booster club, map the coaches for all sports, and reach out to the AD proposing a consolidated brand program to unify their look."}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 204: First Contact',
      'Master cold outreach, scripts, emails, and securing the first meeting.',
      'REP',
      'LEVEL_2_PRODUCT',
      204,
      '## Learning Objective\\nInitiate outreach that breaks through the noise and secures a discovery meeting.\\n\\n## Training Explanation\\nInitiate outreach that breaks through the noise and secures a discovery meeting. First contact is not about pitching products; it is about establishing trust and identifying pain. Leverage TUF commercial insights. Introduce the TUF platform by addressing common vendor friction points: late shipments, poor communication, and complex ordering processes.\\n\\nIf a coach raises the common objection, "We already have a vendor," do not argue. Validate their relationship, then position TUF as a solution for their main headaches, such as mid-season replacement delays or complex parent ordering.\\n\\n## Rep Actions\\n1. Draft your cold outreach email and call script templates.\\n2. Call the AD or Coach using the direct scripts provided.\\n3. Secure a 10-minute discovery call or meeting.\\n\\n## Field Language\\nObjection Handling: "Coach, I know you are busy preparing for the season. I work with TUF helping local programs simplify custom uniform ordering. What was your biggest headache with your last vendor delivery?"\\n\\n## What Done Means\\nPass the first contact quiz and practice cold calling scripts.\\n\\n## Practical Checkpoint\\nWrite a personalized first contact email template addressing a local head coach.',
      25,
      'MODULE',
      '[{"question": "You call a head football coach who immediately says, \\"We\'\'ve used the same local team dealer for 12 years and aren\'\'t interested in changing.\\" What is the best script to handle this objection?", "options": ["\\"We are 20% cheaper than your local dealer and our fabrics are superior.\\"", "\\"I respect that, Coach. Long-term partnerships are rare. I\'\'m not asking you to switch. I just want to show you how we handle 7-day mid-season replacement orders when your main dealer takes 6 weeks. Can we do a 10-minute call next Tuesday?\\"", "\\"Local dealers are outdated. You should switch to a digital-first vendor like TUF.\\"", "\\"No problem, Coach. Let me know if they ever mess up an order and I\'\'ll send you a quote.\\""], "correctAnswer": "\\"I respect that, Coach. Long-term partnerships are rare. I\'\'m not asking you to switch. I just want to show you how we handle 7-day mid-season replacement orders when your main dealer takes 6 weeks. Can we do a 10-minute call next Tuesday?\\""}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 205: Discovery',
      'Uncover athletic budget constraints, vendor pain points, and sport timelines.',
      'REP',
      'LEVEL_2_PRODUCT',
      205,
      '## Learning Objective\\nConduct structured discovery to diagnose potential client pain points and buying readiness.\\n\\n## Training Explanation\\nConduct structured discovery to diagnose potential client pain points and buying readiness. Never lead with products or pricing. Lead with diagnostic questions to uncover current vendor friction: "What was your biggest headache with your last uniform delivery timeline?" Use the gaps discovered to position TUF solutions.\\n\\nUncover the school\'\'s budget constraints, purchasing approval steps, and key sport timelines. Always ask about their previous vendor\'\'s delivery reliability and how mid-season replacement orders were handled, especially for late roster additions.\\n\\n## Rep Actions\\n1. Prepare diagnostic discovery questions before calling.\\n2. Ask open-ended questions about budget timelines, booster approvals, and custom color rules.\\n3. Listen for timing, quality, and service pain points.\\n\\n## Field Language\\nDiscovery questions: "How did your last vendor handle mid-season replacement orders? Did families face shipping delays with their parent orders?"\\n\\n## What Done Means\\nPass the discovery quiz and demonstrate understanding of objectives-based diagnostics.\\n\\n## Practical Checkpoint\\nDraft three discovery questions targeting vendor service reliability and order replacement speed.',
      25,
      'MODULE',
      '[{"question": "You are in a discovery meeting with a baseball coach. Which of the following questions is most effective for diagnosing logistical pain and qualifying their order needs?", "options": ["\\"Would you purchase uniforms from us if we could beat your current supplier\'\'s price?\\"", "\\"What was the process and timeline when you had late-season roster additions last year, and how did your vendor handle those replacement jersey orders?\\"", "\\"Do you prefer custom sublimation or traditional screen printing on polyester?\\"", "\\"Can you send me a list of all your players\'\' sizes and numbers so I can write a quote?\\""], "correctAnswer": "\\"What was the process and timeline when you had late-season roster additions last year, and how did your vendor handle those replacement jersey orders?\\""}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 206: Presentations & Mockups',
      'Create high-converting mockup requests and present visual custom designs to coaches.',
      'REP',
      'LEVEL_2_PRODUCT',
      206,
      '## Learning Objective\\nConvert interest into visual design requests using our design desk.\\n\\n## Training Explanation\\nConvert interest into visual design requests using our design desk. Custom mockups are our highest-converting sales trigger. However, mockups are resource-intensive. To protect our design team\'\'s workload, you must qualify the opportunity through the Mockup Discovery Gate.\\n\\nThe Mockup Discovery Gate requires: (1) Confirming that you are working with the decision-maker (AD or Coach), (2) Identifying the target purchase season and intent to buy, and (3) Collecting the official high-resolution vector logos and Pantone color codes. Never submit a mockup request without these three elements.\\n\\n## Rep Actions\\n1. Verify the lead has passed all three criteria of the Mockup Discovery Gate.\\n2. Collect high-resolution vector logos and Pantone color codes from the school.\\n3. Log in to TUF Ops, create a mockup request, and upload the graphic assets.\\n\\n## Field Language\\nPresenting the design: "Coach, our design desk put together this custom uniform concept matching your tradition. We have this engineered with TUF GRIND fabric to ensure it looks and performs beautifully all season."\\n\\n## What Done Means\\nSubmit a mockup request inside TUF Ops with complete vector assets and get coach sign-off.\\n\\n## Practical Checkpoint\\nVerify you know where to upload mockup assets and request a custom design version.',
      25,
      'MODULE',
      '[{"question": "A basketball coach is interested in seeing custom designs but doesn\'\'t have the high-resolution vector files and has not confirmed their budget. How do you handle this mockup request?", "options": ["\\"Submit the mockup request immediately using low-resolution screenshots to keep the deal moving.\\"", "\\"Explain to the coach that to create an accurate design, we need to gather the official vector logos and confirm their buying timeline, guiding them through the Mockup Discovery Gate first.\\"", "\\"Draw the logo yourself and submit a mockup request to the Brand team.\\"", "\\"Refuse to work with the coach until they pay a design deposit.\\""], "correctAnswer": "\\"Explain to the coach that to create an accurate design, we need to gather the official vector logos and confirm their buying timeline, guiding them through the Mockup Discovery Gate first.\\""}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 207: Closing Business',
      'Overcome final hurdles, secure design approval, and transition to orders.',
      'REP',
      'LEVEL_2_PRODUCT',
      207,
      '## Learning Objective\\nWalk coaches through final mockup approvals, size selections, and order submissions.\\n\\n## Training Explanation\\nWalk coaches through final mockup approvals, size selections, and order submissions. Closing is about coordination. Review the mockups together, confirm quantities, order deadlines, and have them sign the mockup sign-off. This transitions the deal from opportunity to active order.\\n\\nWe maintain a strict 45% Gross Margin Floor on all orders. TAEs can offer up to a 10% discount to secure high-value orders, but this requires written approval from the Regional Director and must still remain above the 45% margin floor. Any discount greater than 10% is prohibited.\\n\\n## Rep Actions\\n1. Conduct the final mockup review session with the head coach and athletic director.\\n2. Distribute sizing kits to the team and collect completed size lists.\\n3. Verify that the order\'\'s gross margin is at least 45% before final submission.\\n\\n## Field Language\\n"Coach, once you sign off on this design and confirm the size list, we will submit the order directly to production. Our Pakistan facility will have these sublimated uniforms ready in 4 weeks."\\n\\n## What Done Means\\nSecure final mockup approval, size verification, and submit the order in TUF Ops.\\n\\n## Practical Checkpoint\\nEnsure the order meets the 45% gross margin floor and has all required signatures.',
      25,
      'MODULE',
      '[{"question": "You are closing a football uniform order. The coach requests a 12% discount to fit their remaining booster budget, which would result in a 46% gross margin. How must you handle this?", "options": ["\\"Apply the 12% discount since the gross margin remains above the 45% floor.\\"", "\\"Explain that the absolute maximum discount is 10% and requires written Director approval, keeping the margin above the 45% floor, and work with them to adjust the order quantities to fit their budget.\\"", "\\"Request that the Operations department manually override the system to apply the 12% discount.\\"", "\\"Refuse any discount and tell the coach that TUF does not negotiate on price.\\""], "correctAnswer": "\\"Explain that the absolute maximum discount is 10% and requires written Director approval, keeping the margin above the 45% floor, and work with them to adjust the order quantities to fit their budget.\\""}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 208: Account Expansion',
      'Sell multi-sport solutions, team stores, coaches gear, travel programs, and letterman jackets.',
      'REP',
      'LEVEL_2_PRODUCT',
      208,
      '## Learning Objective\\nExpand a single uniform order into a multi-lane relationship.\\n\\n## Training Explanation\\nExpand a single uniform order into a multi-lane relationship. Leverage a successful football uniform delivery. Immediately introduce coaches gear, parent/fan team stores, travel programs, and letterman jackets. Expansion turns a small transactional relationship into a major account.\\n\\nUse our Ecosystem Referral Script on every account review. Ask the varsity coach for introductions to their middle school and youth feeder league directors. This expands your sales footprint, standardizes branding across all age groups, and routes 5% of youth store sales back to the varsity booster club.\\n\\n## Rep Actions\\n1. Follow up with coaches 30 days after uniform delivery to ensure satisfaction.\\n2. Pitch a digital fan gear store to the booster club for parent orders.\\n3. Use the Ecosystem Referral Script to get introductions to feeder program directors.\\n\\n## Field Language\\nEcosystem Referral Script: "Coach, now that we have your varsity squad set up with their game kits, we want to make sure the middle school and youth feeder programs are running the exact same brand assets. Who is the director of your youth association? I want to reach out to them, get their kids in the same colors, and route 5% of their team store sales directly back into your varsity booster account."\\n\\n## What Done Means\\nPass the account expansion quiz and demonstrate ability to secure feeder program leads.\\n\\n## Practical Checkpoint\\nDraft an email to a booster club president proposing a seasonal fan gear store.',
      30,
      'MODULE',
      '[{"question": "You successfully delivered custom track jerseys to a varsity team. What is the most effective play to execute the Ecosystem Referral Script and expand the account?", "options": ["Ask the head coach for introductions to the local youth track club directors to align their branding and set up a team store that routes 5% of sales back to the varsity team.", "Move on to another school district immediately to find new opportunities.", "Wait until next season to see if they need to replace worn-out jerseys.", "Pitch the track coach on buying custom football jerseys for the school\'\'s football team."], "correctAnswer": "Ask the head coach for introductions to the local youth track club directors to align their branding and set up a team store that routes 5% of sales back to the varsity team."}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 301: Lane Penetration',
      'Understand that One School = Multiple Lanes, and map individual sport/product revenue streams.',
      'REP',
      'LEVEL_3_TERRITORY',
      301,
      '## Learning Objective\\nAdopt the core mindset: One School \u2260 One Sale. One School = Multiple Lanes.\\n\\n## Core Lesson\\nEvery school has independent revenue streams: Football uniforms, basketball jerseys, baseball gear, booster stores, and letterman jackets. To penetrate a territory, you must map and win these lanes independently.',
      25,
      'MODULE',
      '[{"question": "What does Lane Penetration mean in the TUF operating model?", "options": ["Driving in the fast lane to school visits", "Expanding beyond a single sport or product line to capture multiple lanes in a school", "Limiting sales to one sport per school", "Selling only letterman jackets"], "correctAnswer": "Expanding beyond a single sport or product line to capture multiple lanes in a school"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 302: Feeder Program Extraction',
      'Tap youth football leagues, club volleyball, travel basketball, and community sports.',
      'REP',
      'LEVEL_3_TERRITORY',
      302,
      '## Learning Objective\\nMap and target youth programs feeding into your territory high schools.\\n\\n## Core Lesson\\nYouth leagues, middle schools, and club travel programs feed directly into high school systems. Winning these feeder programs establishes brand loyalty early, increases revenue, and expands your territory footprint.',
      25,
      'MODULE',
      '[{"question": "How do youth feeder programs benefit your high school account?", "options": ["They have no connection to high schools", "They build early brand loyalty and expand your lane revenue to younger age brackets", "They are run directly by the school principal", "They replace the high school team store"], "correctAnswer": "They build early brand loyalty and expand your lane revenue to younger age brackets"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 303: Building a TUF School',
      'Turn a single account into a multi-lane, multi-year relationship.',
      'REP',
      'LEVEL_3_TERRITORY',
      303,
      '## Learning Objective\\nTransform accounts into long-term strategic partners.\\n\\n## Core Lesson\\nA \u201cTUF School\u201d is an account with multiple active lanes, youth feeder alignments, and a long-term preferred vendor relationship. Transition accounts from simple buyers to fully integrated TUF Schools.',
      30,
      'MODULE',
      '[{"question": "What distinguishes a \'\'TUF School\'\' from a standard account?", "options": ["A school with a single active uniform order", "A school with multiple active lanes, youth feeders, and a long-term relationship with TUF", "Any school within your assigned territory", "A school that has locked you out"], "correctAnswer": "A school with multiple active lanes, youth feeders, and a long-term relationship with TUF"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 401: From Rep to Leader',
      'Transition from individual contributor to coaching and guiding other reps.',
      'REP',
      'LEVEL_4_SALES',
      401,
      '## Learning Objective\\nTransition from managing your own territory to leading, enabling, and scaling a team of reps.\\n\\n## Core Lesson\\nAs a Director, your success is measured by the performance of your Territory Account Executives. Focus on system adherence, accountability, and metric tracking.',
      30,
      'MODULE',
      '[{"question": "What is the primary shift in responsibility when moving from Rep to Director?", "options": ["Doing all the selling yourself", "Enabling and coaching your team of reps to perform at their best", "Working fewer hours", "Ignoring company operations"], "correctAnswer": "Enabling and coaching your team of reps to perform at their best"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 402: Coaching Conversations',
      'Run structured pipeline reviews and rubrics-based coaching.',
      'REP',
      'LEVEL_4_SALES',
      402,
      '## Learning Objective\\nLearn to host effective coaching sessions using rubric-based frameworks.\\n\\n## Core Lesson\\nDo not just ask \\"When will this deal close?\\" Instead, use standard rubrics to review active opportunities: next action dates, contact depth, lanes identified, and potential friction notes.',
      25,
      'MODULE',
      '[{"question": "How should a Director guide a rep during a coaching conversation?", "options": ["Tell them exactly what to do without asking questions", "Use rubric-based questions to help them identify next steps and expansion paths", "Do the sales calls for them", "Reprimand them for any deal delays"], "correctAnswer": "Use rubric-based questions to help them identify next steps and expansion paths"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 403: Territory Management',
      'Plan coverage, allocate leads, and monitor regional metrics.',
      'REP',
      'LEVEL_4_SALES',
      403,
      '## Learning Objective\\nManage and optimize the school books and leads in your territory scope.\\n\\n## Core Lesson\\nEnsure optimal account coverage. Reassign untouched schools, track activity streaks, identify high-risk accounts, and coordinate resource allocation for regional campaigns.',
      25,
      'MODULE',
      '[{"question": "What is the main goal of director-level territory management?", "options": ["Letting reps pick schools randomly", "Ensuring optimal account coverage, assigning lead pools, and monitoring territory health", "Taking over the top accounts for yourself", "Closing low-value opportunities"], "correctAnswer": "Ensuring optimal account coverage, assigning lead pools, and monitoring territory health"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 404: Academy Certification',
      'Manage rep onboarding, checkoff requirements, and system unlocks.',
      'REP',
      'LEVEL_4_SALES',
      404,
      '## Learning Objective\\nUnderstand the certification criteria and sign-off process for new reps.\\n\\n## Core Lesson\\nVerify all four certification blocks before signing off on a rep: completed Academy playbooks, filed HR paperwork, passed Locker Room simulator scenarios, and Director verification.',
      25,
      'MODULE',
      '[{"question": "What four requirements must a Director verify before a rep is activated?", "options": ["Completed playbooks, HR docs, practical exercise, and director sign-off", "First sale, vector logo upload, quiz score, and phone log", "Sample kit delivery, phone call, simulation pass, and signature", "CRM account creation, profile photo, bio, and email"], "correctAnswer": "Completed playbooks, HR docs, practical exercise, and director sign-off"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 405: Performance Management',
      'Manage performance standards, scorecards, and accountability.',
      'REP',
      'LEVEL_4_SALES',
      405,
      '## Learning Objective\\nIdentify and correct performance gaps within your sales team.\\n\\n## Core Lesson\\nWhen a rep falls below the 4-orders-per-month standard, review activity inputs: daily prospect touches, note completeness, next action dates, and simulator practice sessions.',
      25,
      'MODULE',
      '[{"question": "What standard should be reviewed when a rep falls below the monthly floor?", "options": ["Daily prospecting touches, CRM note quality, next action dates, and simulator practice", "Changing their role to Admin", "Giving them free orders", "Telling them to stop calling schools"], "correctAnswer": "Daily prospecting touches, CRM note quality, next action dates, and simulator practice"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 501: Building Leaders',
      'Develop Directors and build leadership depth.',
      'REP',
      'LEVEL_5_EXPANSION',
      501,
      '## Learning Objective\\nIdentify and develop Territory Account Executives into capable Directors.\\n\\n## Core Lesson\\nRegional Directors build leaders. Train directors in performance management, coaching frameworks, and systems accountability to build leadership depth in your region.',
      30,
      'MODULE',
      '[{"question": "What is a Regional Director\'\'s role in building leaders?", "options": ["Coaching Directors on performance management and coaching skills", "Selling to school districts", "Managing individual rep pipelines", "Creating marketing flyers"], "correctAnswer": "Coaching Directors on performance management and coaching skills"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 502: Recruiting Systems',
      'Identify, recruit, and onboard talent.',
      'REP',
      'LEVEL_5_EXPANSION',
      502,
      '## Learning Objective\\nDeploy structured hiring and onboarding systems to scale your territory.\\n\\n## Core Lesson\\nUse systematic, rubric-based recruiting. Look for self-sufficient territory developers who demonstrate ownership, sales discipline, and alignment with TUF values.',
      25,
      'MODULE',
      '[{"question": "What is key to recruiting successful reps?", "options": ["Hiring based on resume alone", "Using structured competency assessments and seeking self-sufficient territory developers", "Selecting people who only want passive income", "Automated hiring without interviews"], "correctAnswer": "Using structured competency assessments and seeking self-sufficient territory developers"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 503: Regional Expansion',
      'Launch new territories and scale regional presence.',
      'REP',
      'LEVEL_5_EXPANSION',
      503,
      '## Learning Objective\\nScale operations by launching adjacent and new geographic territories.\\n\\n## Core Lesson\\nRegional expansion depends on playbook replication. Hire a native territory developer, seed them with standard playbooks, connect them with our operations desk, and support them through local leadership.',
      25,
      'MODULE',
      '[{"question": "How do you scale regional operations effectively?", "options": ["By duplicating standard operating playbooks and recruiting native leaders in new territories", "By expanding without local leaders", "By lowering commission rates", "By selling uniforms at lower margins"], "correctAnswer": "By duplicating standard operating playbooks and recruiting native leaders in new territories"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 601: The Founder Trap',
      'Move from founder-led sales to scalable, process-driven leadership layers.',
      'REP',
      'SPECIALIZED_TRACKS',
      601,
      '## Learning Objective\\nTransition the organization from founder-led sales to a systemized, process-driven architecture.\\n\\n## Core Lesson\\nThe Founder Trap occurs when all operations depend on a single founder\'\'s personal energy. Escaping this requires documented playbooks, certified leadership layers, and standardized accountability.',
      30,
      'MODULE',
      '[{"question": "How do you escape the \'\'Founder Trap\'\'?", "options": ["Founder makes all the major decisions forever", "Building systemized processes, playbooks, and delegating authority to certified leaders", "Selling the company", "Hiring more administrative assistants"], "correctAnswer": "Building systemized processes, playbooks, and delegating authority to certified leaders"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 602: Leadership Layers',
      'Structure the organization for long-term growth and accountability.',
      'REP',
      'SPECIALIZED_TRACKS',
      602,
      '## Learning Objective\\nUnderstand the coordination between Sales, Operations, and Brand leadership layers.\\n\\n## Core Lesson\\nStructure clear growth and accountability paths. Build functional leadership layers that coordinate sales enablement, product fulfillment, and brand integrity.',
      25,
      'MODULE',
      '[{"question": "What is the purpose of structured leadership layers at TUF?", "options": ["To slow down decision-making", "To align authority, coordinate sales/operations/brand, and foster professional growth paths", "To replace all human interactions with AI", "To eliminate the need for training"], "correctAnswer": "To align authority, coordinate sales/operations/brand, and foster professional growth paths"}]'::jsonb,
      85,
      NOW(),
      NOW()
    ),
    (
      'Playbook 603: Building The TUF Ecosystem',
      'Develop high-level partnerships and expand the global TUF ecosystem.',
      'REP',
      'SPECIALIZED_TRACKS',
      603,
      '## Learning Objective\\nFormulate the long-term strategic vision for the global TUF Ecosystem.\\n\\n## Core Lesson\\nOur goal is to build an interconnected ecosystem spanning team apparel, community sports, equipment partnerships, and media channels, establishing TUF as the operating system for school athletics.',
      30,
      'MODULE',
      '[{"question": "What is the ultimate vision of the TUF Ecosystem?", "options": ["Creating an interconnected apparel, equipment, and media network that dominates school athletics", "Becoming a small local supplier", "Selling direct-to-consumer only", "Focusing on custom socks"], "correctAnswer": "Creating an interconnected apparel, equipment, and media network that dominates school athletics"}]'::jsonb,
      85,
      NOW(),
      NOW()
    );
  \`);
};

exports.down = async (pgm) => {
  pgm.sql(`
    DELETE FROM training_modules;
  `);
};
