/**
 * TUF Ops 2.0 — `Task` (Wave 5A, ADDITIVE).
 *
 * A Task is the concrete "what needs to be done" generated by the deterministic
 * task engine (never by an AI/model). Every Task belongs to a Market
 * (`markets.id`) and is produced by a state transition resolving a declarative
 * lookup table (state -> task template). See apps/api/src/modules/tasks.
 *
 * `taskKey` is the deterministic idempotency key: re-running the same
 * transition while the generated task is still OPEN does NOT create a duplicate
 * (enforced by a partial UNIQUE index on (market_id, task_key) WHERE OPEN).
 */

/** Task lifecycle. Kept deliberately small. */
export enum TaskState {
  OPEN = 'OPEN',
  DONE = 'DONE',
  CANCELLED = 'CANCELLED',
}

export const TASK_STATES: readonly TaskState[] = [
  TaskState.OPEN,
  TaskState.DONE,
  TaskState.CANCELLED,
];

/**
 * The COMMAND ordering bucket of a task's due date, relative to "now":
 *   OVERDUE  -> past due
 *   TODAY    -> due later today
 *   UPCOMING -> due after today
 * COMMAND returns overdue first, then today, then upcoming.
 */
export type TaskBucket = 'OVERDUE' | 'TODAY' | 'UPCOMING';

export const TASK_BUCKETS: readonly TaskBucket[] = ['OVERDUE', 'TODAY', 'UPCOMING'];

/** The entity kind a task's generating transition belongs to. */
export type TaskEntityKind = 'MARKET' | 'LETTERED';

export interface Task {
  id: number;
  /** The Market this task belongs to (references `markets.id`). */
  marketId: number;

  /** Deterministic idempotency key, e.g. `MARKET:DEVELOPMENT`. */
  taskKey: string | null;

  /** The concrete next move. */
  title: string;

  /** When the task is due (ISO-8601). */
  dueAt: string;

  state: TaskState;

  /** Priority carried from the task template (`TIER_1|TIER_2|TIER_3`). */
  priority: string | null;

  /** Provenance, e.g. `ACTIVATION`, `SEED_LAUNCH_2_0`, `TASK_ENGINE`. */
  source: string | null;

  createdBy: number | null;
  completedAt: string | null;
  createdAt: string | null;
  updatedAt: string | null;
}
