import { GlassCard } from '../components/ui';
import type { Role } from '../types';
import { useOpportunities } from '../hooks/useOpportunities';
import { useOrders } from '../hooks/useOrders';
import { useActivities } from '../hooks/useReports';
import { useOrganizations } from '../hooks/useOrganizations';
import { formatCurrency } from '../utils/format';
import { getNearCloseOpportunities, getStuckOpportunities, getLanePenetration } from '../services/businessSelectors';

function FocusPill({ label, value, tone }: { label: string; value: string; tone: 'blue' | 'teal' | 'red' }) {
  const toneClass = tone === 'blue' ? 'from-blue-500/20 to-indigo-500/10 border-blue-400/40' : tone === 'teal' ? 'from-cyan-500/20 to-emerald-500/10 border-cyan-400/40' : 'from-rose-500/18 to-red-500/10 border-rose-400/40';
  return <div className={`rounded-lg border bg-gradient-to-r p-3 ${toneClass}`}><p className="text-2xl font-semibold text-slate-100">{value}</p><p className="text-sm text-slate-200">{label}</p></div>;
}
function ActionRow({ title, subtitle, value }: { title: string; subtitle: string; value: string }) {
  return <div className="flex items-center justify-between rounded-lg border border-slate-800 bg-slate-900/70 px-3 py-2"><div><p className="text-sm font-semibold text-slate-100">{title}</p><p className="text-xs text-slate-400">{subtitle}</p></div><div className="text-right"><p className="text-sm font-semibold text-slate-100">{value}</p><p className="text-xs text-slate-500">›</p></div></div>;
}

function DashboardFrame({ a,b,c, actionsTitle, actions, nearCloseTitle, nearClose, snapshotTitle, snapshotBody, revenueTitle, revenueBody, recentTitle, recent, monthTitle, monthBody }:{a:[string,string,'blue'|'teal'|'red'];b:[string,string,'blue'|'teal'|'red'];c:[string,string,'blue'|'teal'|'red'];actionsTitle:string;actions:any[];nearCloseTitle:string;nearClose:any[];snapshotTitle:string;snapshotBody:React.ReactNode;revenueTitle:string;revenueBody:React.ReactNode;recentTitle:string;recent:any[];monthTitle:string;monthBody:React.ReactNode;}){
  return <div className="space-y-3"><h2 className="text-3xl font-semibold tracking-tight">Today’s Focus</h2><div className="grid gap-2 md:grid-cols-3"><FocusPill label={a[0]} value={a[1]} tone={a[2]}/><FocusPill label={b[0]} value={b[1]} tone={b[2]}/><FocusPill label={c[0]} value={c[1]} tone={c[2]}/></div><div className="grid gap-2 lg:grid-cols-3"><GlassCard title={actionsTitle}><div className="space-y-2">{actions.map((x:any)=><ActionRow key={x.id||x.title} title={x.title} subtitle={x.subtitle} value={x.value}/>)}</div></GlassCard><GlassCard title={snapshotTitle}>{snapshotBody}</GlassCard><GlassCard title={revenueTitle}>{revenueBody}</GlassCard></div><div className="grid gap-2 lg:grid-cols-3"><GlassCard title={nearCloseTitle}><div className="space-y-2">{nearClose.map((x:any)=><ActionRow key={x.id||x.title} title={x.title} subtitle={x.subtitle} value={x.value}/>)}</div></GlassCard><GlassCard title={recentTitle} className="lg:col-span-2"><div className="space-y-2">{recent.map((a:any)=><div key={a.id} className="flex items-center justify-between rounded-lg border border-slate-800 bg-slate-900/60 px-3 py-2 text-sm"><span className="text-slate-200">• {a.message}</span><span className="text-xs text-slate-400">{a.user}</span></div>)}</div></GlassCard></div><GlassCard title={monthTitle}>{monthBody}</GlassCard></div>;
}

function RoleDashboard({ role }: { role: Role }) {
  const opportunities = useOpportunities({}); const orders = useOrders({}); const organizations = useOrganizations({}); const activities = useActivities({ limit: 4 }); const nearClose = getNearCloseOpportunities(opportunities); const stuck = getStuckOpportunities(opportunities); const lane = getLanePenetration(organizations);
  const actionsBase = opportunities.slice(0,3).map(o=>({id:o.id,title:o.nextAction,subtitle:o.organizationName,value:formatCurrency(o.value)}));
  const nearBase = nearClose.slice(0,3).map(o=>({id:o.id,title:o.organizationName,subtitle:o.nextAction,value:formatCurrency(o.value)}));
  if(role==='REP') return <DashboardFrame a={['Deals Need Action',String(opportunities.length),'blue']} b={['Near Close',String(nearClose.length),'teal']} c={['Payments Pending',String(opportunities.filter(o=>o.stage==='INVOICE_SENT').length),'red']} actionsTitle="NEXT ACTIONS" actions={actionsBase} nearCloseTitle="DEALS NEAR CLOSE" nearClose={nearBase} snapshotTitle="PIPELINE SNAPSHOT" snapshotBody={<div className='text-sm text-slate-300'>Contacted {formatCurrency(opportunities.filter(o=>o.stage==='CONTACTED').reduce((a,b)=>a+b.value,0))}<br/>Mockup {formatCurrency(opportunities.filter(o=>o.stage==='MOCKUP_DELIVERED').reduce((a,b)=>a+b.value,0))}<br/>Invoice {formatCurrency(opportunities.filter(o=>o.stage==='INVOICE_SENT').reduce((a,b)=>a+b.value,0))}</div>} revenueTitle="REVENUE" revenueBody={<div className='text-sm text-slate-300'>Closed {formatCurrency(opportunities.filter(o=>o.stage==='CLOSED_WON').reduce((a,b)=>a+b.value,0))}<br/>Pending {formatCurrency(opportunities.filter(o=>o.stage==='INVOICE_SENT').reduce((a,b)=>a+b.value,0))}</div>} recentTitle="RECENT ACTIVITY" recent={activities} monthTitle="THIS MONTH" monthBody={<p className='text-sm text-slate-300'>2 / 4 Orders</p>} />;
  if(role==='OWNER') return <DashboardFrame a={['Revenue at Risk',formatCurrency(stuck.reduce((a,b)=>a+b.value,0)),'red']} b={['Near Close Pipeline',formatCurrency(nearClose.reduce((a,b)=>a+b.value,0)),'teal']} c={['Payments Pending',String(opportunities.filter(o=>o.stage==='INVOICE_SENT').length),'blue']} actionsTitle="STRATEGIC ALERTS" actions={stuck.slice(0,3).map(o=>({id:o.id,title:o.organizationName,subtitle:o.nextAction,value:formatCurrency(o.value)}))} nearCloseTitle="TOP OPPORTUNITIES" nearClose={nearBase} snapshotTitle="LANE PENETRATION" snapshotBody={<p className='text-sm text-slate-300'>Uniform {lane.UNIFORM} · Travel {lane.TRAVEL_GEAR} · Store {lane.TEAM_STORE} · Letterman {lane.LETTERMAN}</p>} revenueTitle="REVENUE OVERVIEW" revenueBody={<p className='text-sm text-slate-300'>Open Pipeline {formatCurrency(opportunities.reduce((a,b)=>a+b.value,0))}</p>} recentTitle="RECENT ACTIVITY" recent={activities} monthTitle="LEADERSHIP PRIORITY" monthBody={<p className='text-sm text-slate-300'>Unblock stuck deals and expand lane coverage.</p>} />;
  if(role==='DIRECTOR') return <DashboardFrame a={['Stuck Deals',String(stuck.length),'red']} b={['Reps Needing Coaching',String(Math.max(1,stuck.length)),'blue']} c={['Near Close',String(nearClose.length),'teal']} actionsTitle="MY OPPORTUNITIES SUMMARY" actions={actionsBase} nearCloseTitle="TEAM OPPORTUNITIES SUMMARY" nearClose={nearBase} snapshotTitle="ACCOUNTS NEEDING ACTION" snapshotBody={<p className='text-sm text-slate-300'>{stuck.length + nearClose.length} accounts require follow-up today.</p>} revenueTitle="TERRITORY COVERAGE" revenueBody={<p className='text-sm text-slate-300'>Uniform {lane.UNIFORM} · Travel {lane.TRAVEL_GEAR} · Store {lane.TEAM_STORE} · Letterman {lane.LETTERMAN}</p>} recentTitle="RECENT REP ACTIVITY" recent={activities} monthTitle="WEEKLY COACHING SUMMARY" monthBody={<p className='text-sm text-slate-300'>Coach stuck + near-close deals in daily 1:1 cadence.</p>} />;
  return <DashboardFrame a={['New Orders',String(orders.filter(o=>o.productionStatus==='NEEDS_REVIEW').length),'blue']} b={['Missing Info',String(orders.filter(o=>o.missingInfo.length).length),'teal']} c={['Blocked Orders',String(orders.filter(o=>o.productionStatus==='BLOCKED').length),'red']} actionsTitle="READY FOR VENDOR" actions={orders.filter(o=>o.productionStatus==='READY_FOR_VENDOR').slice(0,3).map(o=>({id:o.id,title:o.organizationName,subtitle:o.productionStatus,value:formatCurrency(o.value)}))} nearCloseTitle="BLOCKER REASONS" nearClose={orders.filter(o=>o.productionStatus==='BLOCKED').slice(0,3).map(o=>({id:o.id,title:o.organizationName,subtitle:o.missingInfo.join(', ')||'Missing details',value:formatCurrency(o.value)}))} snapshotTitle="IN PRODUCTION" snapshotBody={<p className='text-sm text-slate-300'>{orders.filter(o=>o.productionStatus==='IN_PRODUCTION').length} active orders</p>} revenueTitle="EXECUTION VALUE" revenueBody={<p className='text-sm text-slate-300'>{formatCurrency(orders.reduce((a,b)=>a+b.value,0))}</p>} recentTitle="RECENT HANDOFFS" recent={activities} monthTitle="OPS GOAL" monthBody={<p className='text-sm text-slate-300'>Clear blocked orders within 48 hours.</p>} />;
}

export function DashboardPage({ role }: { role: Role }) { return <RoleDashboard role={role} />; }
